server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: always
number-generator:
  url: http://localhost:9090
---
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: bir
    url: jdbc:postgresql://localhost:5432/orders
    username: bir
  jpa:
    show-sql: true
  liquibase:
    enabled: true
